spring.thymeleaf.cache: false

build:
  info:
    file: classpath:build-info.yml

server:
  servlet:
    contextPath: /api

swagger:
  api:
    title: sample-api
    contact.info: Team
    licence.url: #
    description:
    groupName: sample-api
    version: 1.0
    path:
      regex: /v.*/.*
  terms.of.service.url: #
  enabled: true
  
request:
  logging:
    enabled: true
    verbose: false
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tsp_admin
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
  rabbitmq:
    uri : amqp://opwcbexo:5IZ6Ll-lDVKNXQUJBIwghURM9AlIr2Tw@moose.rmq.cloudamqp.com/opwcbexo
    exchange: testExchange
    routingkey: messages.key
    
useSSL: false
security.enable-csrf: false
subscriberBaseUrl: https://tsp-subscriber-service.cfapps.io/api
crossOrigin: https://tsp-admin-prod.cfapps.io
TSPMailAddress: tsp@notification.com
notifiationBaseUrl: https://tsp-notification-service.cfapps.io/api/
